version: '3.8'

services:
  cloudflare-ai-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    env_file:
      - .env
    volumes:
      # Mount config for hot-swapping models
      - ./configs/model.yaml:/app/configs/model.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-proxy-network

networks:
  ai-proxy-network:
    driver: bridge
