version: '3.8'

services:
  cloudflare-ai-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    env_file:
      - .env
    volumes:
      # Mount entire app for hot reload in development
      - ./app:/app/app:ro
      - ./configs:/app/configs:ro
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    networks:
      - ai-proxy-network

networks:
  ai-proxy-network:
    driver: bridge
