version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    profiles: ["active"]

  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    volumes:
      - .:/app
    restart: unless-stopped
    profiles: ["active"]
