version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage:rw
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

  embedding-api:
    build: .
    container_name: embedding-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - VECTOR_DIM=384
      - COLLECTION_NAME=embeddings
    depends_on:
      - qdrant
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  default:
    driver: bridge
